### ISSUE TITLE
Profile Views not working

### ISSUE THREAD

**Issue by KendallDoesCoding** [TechStudent10/techstudent10#12]
The profile views extension isnt working.

**Comment by KendallDoesCoding** [comment]
@TechStudent11 I think this is a issue with the plugin, they may be on updates. But leaving this open still, incase it isn't. But mostly, it is, because it's not working for me too.

**Comment by TechStudent10** [comment]
![image](https://user-images.githubusercontent.com/76978184/147768932-1f42905f-25ff-480e-8f2b-7a92a14dee59.png)

Oof, it ain't workin'.

**Comment by KendallDoesCoding** [comment]
Yes, their website is down.

**Comment by KendallDoesCoding** [comment]
And I also think, the profile views think is monthly, so it takes your profile views in the month and displays it? So, they may be updating that too, if it's 1st in their timezone.

**Comment by KendallDoesCoding** [comment]
> Yes, their website is down.

![image](https://user-images.githubusercontent.com/84712013/147769072-b621a490-b324-4f2a-8367-09be0aaca4e0.png)

**Comment by TechStudent10** [comment]
maybe

**Comment by KendallDoesCoding** [comment]
Yup, it's back now.
