### ISSUE TITLE
Youtube icon site down

### ISSUE THREAD

**Issue by KendallDoesCoding** [TechStudent10/techstudent10#24]
I made the svg and hosted it on https://svgshare.com/, but it seems their quota is over? I don't have the svg file, but when it come back I will like to download the svg and add it in this repo and link it in the README, and stop using third party sites for this coz they can go down when they feel like lol

**Comment by TechStudent10** [comment]
I can still see it

![image](https://user-images.githubusercontent.com/76978184/153759476-8ca81f12-d092-4a7d-b6e1-857f437ae5f6.png)

**Comment by KendallDoesCoding** [comment]
It was down yesterday... It's back now.
