### ISSUE TITLE
[FEATURE REQUEST] Inculde banner in readme

### ISSUE THREAD

**Issue by KendallDoesCoding** [TechStudent10/techstudent10#25]
Working on making a banner for ya.

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Please share languages which you code in.

**Comment by KendallDoesCoding** [comment]
Here's what I got, you like it?
![TechStudent10 Banner](https://user-images.githubusercontent.com/84712013/154281672-a8813aa4-2ca4-4e80-9f15-03359233dda2.png)

**Comment by TechStudent10** [comment]
haha thanks. I have no idea where you got that background from. The only place I've put it is on my YouTube, but you can't download that.

I mainly program in Python, HTML, CSS and JS. You could throw in React there.

**Comment by KendallDoesCoding** [comment]
You don't know me well. I have tricks :)

Second though, I think inculding the programming kanguages may make it
cluttered, but I will try to just inculde the icons of the coding languages
as most people have in their README.md but in the banner!

**Comment by TechStudent10** [comment]
> You don't know me well. I have tricks :)

👀 That sounds... weird to say the least but alright.

Wait I just remembered, Inspect Element exists.

![image](https://user-images.githubusercontent.com/76978184/154500097-e38281ea-4ae2-4f7b-ac44-9e3d4077e3de.png)

**Comment by KendallDoesCoding** [comment]
> > You don't know me well. I have tricks :)
> 
> 👀 That sounds... weird to say the least but alright.
> 
> Wait I just remembered, Inspect Element exists.
> 
> ![image](https://user-images.githubusercontent.com/76978184/154500097-e38281ea-4ae2-4f7b-ac44-9e3d4077e3de.png)

I didn't do that... I went to a website to download channel banners, but I think it took me to that exact url 🤣

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Are you adding the banner to README.md or should I close this issue, if you don't like the banner?

**Comment by TechStudent10** [comment]
Well I would add it IF you added it in the form of a Pull Request instead of an issue

**Comment by KendallDoesCoding** [comment]
> Well I would add it IF you added it in the form of a Pull Request instead of an issue

Ok, will do so! I made the issue becoz I didn't know if you would like the banner I made/if you wanted to make one yourself, so this was the issue with the idea... Closing with make a PR shortly.
